name: Docker image

on:
  push:
    branches:
      - master
  pull_request:
  release:
    types: [published]

permissions:
  contents: write
  packages: write

jobs:
  metadata:
    name: Get metadata
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Version
        id: version
        run: |
          if ${{ startsWith(github.ref, 'refs/tags/') }}; then
            echo "version=$(git describe --tags `git rev-list --tags --max-count=1`)" >> "$GITHUB_OUTPUT"
          else
            echo "version=devel" >> "$GITHUB_OUTPUT"
          fi

  test:
    name: Test build image
    runs-on: ubuntu-22.04
    needs: metadata
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 #v3.10.0
      - name: Try build image
        run: |
          docker buildx build .

  publish:
    name: Build and push image
    runs-on: ubuntu-22.04
    needs: [ metadata, test ]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 #v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 #v3.10.0

      - name: Build and push
        uses: docker/build-push-action@1dc73863535b631f98b2378be8619f83b136f4a0 #v6.17.0
        with:
          context: .
          push: true
          tags: "ghcr.io/daydream-minecraft/server:latest,ghcr.io/daydream-minecraft/server:${{ needs.metadata.outputs.version }}"
